### ISSUE TITLE
need help on geotiff reader

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/go-tc-consequences#2]
I think i have it right, but i dont know if we need to worry about projections and transformations

https://github.com/HydrologicEngineeringCenter/go-tc-consequences/blob/4e31d1881b3d63bdd81c27ace9a09a365d95b8ad/nhc/nhc-processor.go#L20

a sample file is stored here:
https://www.nhc.noaa.gov/gis/inundation/forecasts/AL1320_19_inundation.zip

**Comment by rgoss** [comment]
- if you would like to have a "Location" argument and support multiple projections, I propose to change the struct name to "Location" and define it as

`
type Location struct {
	X float64
	Y float64
	SRID string
} 
`

where the SRID string is the combination of authority:number.  for example 'EPSG:4326'
